# Generated for SwiftLint: 0.16.1
---
disabled_rules:
  - todo
  - large_tuple
opt_in_rules:
  - cyclomatic_complexity
  - empty_count
  - force_unwrapping
  - vertical_whitespace
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
statement_position:
  statement_mode: uncuddled_else
function_parameter_count:
  warning: 6
  error: 8
line_length:
  warning: 126 # github line wrap
  error: 200
colon:
  apply_to_dictionaries: false
